# La mitad DERECHA es la central (la del trackpad): ahí va ZMK Studio.
# La izquierda es periférica y no necesita el snippet.
---
include:
  - board: nice_nano_v2
    shield: cornecirque_left
  - board: nice_nano_v2
    shield: cornecirque_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: settings_reset
