manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: oscar
      url-base: https://github.com/pgzoscar43601
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    # Fork propio del driver del Cirque, 7-sep-2026.
    # El original (petejohanson) lleva sin mantenimiento desde feb-2025 y tiene
    # dos fallos que hacian que el trackpad se congelara y fuera a 16 lecturas
    # por segundo. Ver el README del fork.
    - name: cirque-input-module
      remote: oscar
      revision: aae71d5955f796bde5d358bf6506b5511c57c267
  self:
    path: config
